# Replace organization and projectKey after importing the repo in SonarCloud.
# Example: sonar.organization=my-github-org
#          sonar.projectKey=my-github-org_cs-diploma

sonar.projectKey=Serhii-Smoliak_cs-diploma
sonar.organization=serhii-smoliak

sonar.qualitygate.wait=true

sonar.sources=client/src,server/src,shared/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/prisma/migrations/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info
sonar.sourceEncoding=UTF-8

sonar.javascript.node.maxspace=4096
