/** Full MITRE technique descriptions for operation_ghost missions (en + uk). */
export const MITRE_TECHNIQUE_DESCRIPTIONS = {
  en: {
    'technique.description.T1593':
      'Adversaries may search freely available websites and/or domains for information about victims that can be used during targeting. Information about victims may be available in various online sites, such as social media, news sites, or those hosting information about business operations such as hiring or requested/rewarded contracts. Adversaries may search in different online sites depending on what information they seek to gather. Information from these sources may reveal opportunities for other forms of reconnaissance, establishing operational resources, and/or initial access.',
    'technique.description.T1583.001':
      'Adversaries may acquire domains that can be used during targeting. Domain names are the human readable names used to represent one or more IP addresses. They can be purchased or, in some cases, acquired for free. Adversaries may use acquired domains for phishing, drive-by compromise, and command and control. They may choose domains similar to legitimate ones, including homoglyphs or different top-level domains. Typosquatting helps deliver payloads via drive-by compromise. Adversaries may also use internationalized domain names and similar character sets for homograph attacks. They may acquire expired domains with existing reputation, use private WHOIS to hide ownership, or register domains in compromised cloud environments.',
    'technique.description.T1566.001':
      'Adversaries may send spearphishing emails with a malicious attachment in an attempt to gain access to victim systems. This variant relies on malware attached to an email and usually depends on user execution after opening the file. Attachments may include Office documents, executables, PDFs, or archives. The email text gives a plausible reason to open the file and may explain how to bypass protections or decrypt a password-protected archive. Adversaries often manipulate extensions and icons so executables look like documents.',
    'technique.description.T1059.001':
      'Adversaries may abuse PowerShell commands and scripts for execution. PowerShell is a powerful command-line interface and scripting environment in Windows. Adversaries use it for discovery and code execution, including downloading and running executables from the Internet from disk or in memory. PowerShell can also be invoked without powershell.exe through .NET interfaces to the underlying automation assembly.',
    'technique.description.T1547.001':
      'Adversaries may achieve persistence by adding a program to a startup folder or referencing it with a Registry run key. Adding an entry to run keys or the startup folder causes the program to execute when a user logs in, under that user\'s permissions. Default Windows run keys include HKCU and HKLM Run and RunOnce paths. Startup folders exist per user and system-wide. Adversaries may also use RunServices, Policies\\Explorer\\Run, BootExecute, and related locations to launch malware after reboot and may masquerade entries as legitimate programs.',
  },
  uk: {
    'technique.description.T1593':
      'Зловмисники можуть шукати на вільно доступних веб-сайтах і доменах інформацію про жертв для подальшого таргетингу. Такі дані часто є в соцмережах, новинних ресурсах або сайтах про бізнес-діяльність (найм, контракти, тендери). Залежно від цілей обирають різні джерела. Отримана інформація може відкрити шлях до інших видів розвідки, підготовки ресурсів і початкового доступу (фішинг, зовнішні сервіси тощо).',
    'technique.description.T1583.001':
      'Зловмисники можуть отримувати домени для використання під час атаки. Доменні імена — це зрозумілі людині адреси, що вказують на IP-адреси; їх можна купити або інколи отримати безкоштовно. Такі домени застосовують для фішингу, drive-by компрометації та C2. Часто обирають імена, схожі на легітимні — typosquatting, інший TLD, homoglyph-атаки з міжнародними доменами. Також використовують прострочені домени з уже довіреною репутацією, приховують власника через private WHOIS або реєструють домени в скомпрометованих хмарних середовищах.',
    'technique.description.T1566.001':
      'Зловмисники можуть надсилати цільовий фішинг зі шкідливим вкладенням, щоб отримати доступ до систем жертви. Цей варіант покладається на виконання файлу користувачем після відкриття листа. Вкладеннями можуть бути документи Office, виконувані файли, PDF або архіви. Текст листа надає правдоподібну причину відкрити файл і інколи пояснює, як обійти захист або розпакувати архів з паролем. Розширення та іконки часто підміняють, щоб exe виглядав як документ.',
    'technique.description.T1059.001':
      'Зловмисники можуть зловживати командами та скриптами PowerShell для виконання коду. PowerShell — потужне CLI та середовище сценаріїв у Windows. Його використовують для розвідки й запуску коду, зокрема завантаження та виконання файлів з Інтернету з диска або в пам’яті. PowerShell можна викликати й без powershell.exe — через .NET-інтерфейси до бібліотеки автоматизації.',
    'technique.description.T1547.001':
      'Зловмисники можуть закріпитися в системі, додавши програму в папку автозапуску або через ключ Run у реєстрі. Запис у Run/RunOnce або Startup запускає програму під час входу користувача з його правами. Типові шляхи — HKCU/HKLM Run і RunOnce, а також системні й персональні папки Startup. Також використовують RunServices, Policies\\Explorer\\Run, BootExecute та інші ключі, щоб пережити перезавантаження; записи можуть маскувати під легітимне ПЗ.',
  },
} as const;
